version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
          - CHANGE_SOURCE=${CHANGE_SOURCE}
          - ENABLE_PHP54=${UPSTREAM_ENABLE_PHP54}
          - ENABLE_PHP55=${UPSTREAM_ENABLE_PHP55}
          - ENABLE_PHP56=${UPSTREAM_ENABLE_PHP56}
          - ENABLE_PHP70=${UPSTREAM_ENABLE_PHP70}
          - ENABLE_PHP71=${UPSTREAM_ENABLE_PHP71}
          - ENABLE_PHP72=${UPSTREAM_ENABLE_PHP72}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      environment:
        - TZ=${TIMEZONE}
      networks:
        - frontend
        - backend

### PHP-FPM ##############################################
    php-fpm:
      build:
        context: ./php-fpm
        args:
          - PHP_VERSION=${PHP_VERSION}
          - SWOOLE_VERSION=${SWOOLE_VERSION}
          - HIREDIS_VERSION=${HIREDIS_VERSION}
          - CHANGE_SOURCE=${CHANGE_SOURCE}
          - COMPOSER_REPO_PACKAGIST=${COMPOSER_REPO_PACKAGIST}
          - HTTP_PROXY=${HTTP_PROXY}
          
          - INSTALL_WKHTMLTOPDF=${PHP_FPM_INSTALL_WKHTMLTOPDF}
          - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
          - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
          - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
          - INSTALL_PDO=${PHP_FPM_INSTALL_PDO}
          - INSTALL_PGSQL=${PHP_FPM_INSTALL_PGSQL}
          - INSTALL_PG_CLIENT=${PHP_FPM_INSTALL_PG_CLIENT}
          - INSTALL_ZIP=${PHP_FPM_INSTALL_ZIP}
          - INSTALL_MBSTRING=${PHP_FPM_INSTALL_MBSTRING}
          - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
          - INSTALL_GD=${PHP_FPM_INSTALL_GD}

          - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
          - INSTALL_HIREDIS=${PHP_FPM_INSTALL_HIREDIS}
          - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
          - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      expose:
        - "9000"
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - TZ=${TIMEZONE}
      networks:
        - backend

### PHP-FPM 54 ##############################################
    php-fpm54:
      build:
        context: ./php-fpm54
        args:
          - SWOOLE_VERSION=${SWOOLE_VERSION}
          - HIREDIS_VERSION=${HIREDIS_VERSION}
          - CHANGE_SOURCE=${CHANGE_SOURCE}
          - COMPOSER_REPO_PACKAGIST=${COMPOSER_REPO_PACKAGIST}
          - HTTP_PROXY=${HTTP_PROXY}

          - INSTALL_WKHTMLTOPDF=${PHP_FPM_INSTALL_WKHTMLTOPDF}
          - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
          - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
          - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
          - INSTALL_PDO=${PHP_FPM_INSTALL_PDO}
          - INSTALL_PGSQL=${PHP_FPM_INSTALL_PGSQL}
          - INSTALL_PG_CLIENT=${PHP_FPM_INSTALL_PG_CLIENT}
          - INSTALL_ZIP=${PHP_FPM_INSTALL_ZIP}
          - INSTALL_MBSTRING=${PHP_FPM_INSTALL_MBSTRING}
          - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
          - INSTALL_GD=${PHP_FPM_INSTALL_GD}

          - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
          - INSTALL_HIREDIS=${PHP_FPM_INSTALL_HIREDIS}
          - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
          - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
          - INSTALL_MCRYPT=${PHP_FPM_INSTALL_MCRYPT}
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      expose:
        - "9054"
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - TZ=${TIMEZONE}
      networks:
        - backend